CREATE TABLE USERS
(
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY(USERNAME)
);

CREATE TABLE COMMENT(
    ID INT NOT NULL,
    IMAGEID INT,
    USERNAME VARCHAR(255),
    TEXT VARCHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE IMAGE(
    ID INT DEFAULT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255),
    FILELOCATION VARCHAR(255),
    UPLOADDATE TIMESTAMP,
    DESC VARCHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE FOLLOW(
  followerusername VARCHAR(255) NOT NULL,
  hostusername VARCHAR(255) NOT NULL,
  PRIMARY KEY(followerusername , hostusername )
);

